# Generated by Django 4.2.7 on 2026-10-02 22:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_backfill_variant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paise', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mrp_paise', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_label', models.CharField(default='system', max_length=100)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.productvariant')),
            ],
            options={
                'verbose_name_plural': 'Price history',
                'ordering': ['-effective_from', '-id'],
                'indexes': [models.Index(fields=['variant', 'effective_from'], name='catalog_pri_variant_d35ea5_idx')],
            },
        ),
    ]
