"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from environs import Env
import os
import dj_database_url

env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY: every secret comes from the environment (see backend/.env.example).
SECRET_KEY = env.str("DJANGO_SECRET_KEY")

DEBUG = env.bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])

# Render (and most hosts) give the service its own public hostname at run time. Adding it
# automatically means one less value to copy by hand, and a rename cannot lock you out.
RENDER_EXTERNAL_HOSTNAME = env.str("RENDER_EXTERNAL_HOSTNAME", default="")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=["http://127.0.0.1:8000", "http://localhost:8000"])
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'drf_yasg',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    # Custom Apps
    'core',
    'catalog',
    'inventory',
    'userauths',
    'store',
    'vendor',
    'customer',
    'addon',
    'api',

    # Third Party Apps
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'import_export',
    'anymail',
    'storages',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves the admin's own CSS and JavaScript straight from Django. Needed on hosts where
    # nothing else serves /static/ (Render, Railway); harmless behind Caddy or nginx.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # Add Cors Middle ware here
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.RequestActorMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


db_from_env = dj_database_url.config(conn_max_age=600)
DATABASES['default'].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Uploaded product photos.
#
#   CLOUDINARY_URL set   -> Cloudinary (a free account is enough for a small catalogue)
#   not set              -> this machine's own media/ folder, as in development
#
# A host with no persistent disk (Render's free tier, for example) wipes uploads on every
# deploy and every restart, so a store running there MUST have CLOUDINARY_URL set or its
# product photos will disappear. Nothing else in the project changes: Django keeps writing to
# `ImageField`s exactly as before.
CLOUDINARY_URL = env.str("CLOUDINARY_URL", default="")
USE_CLOUDINARY = bool(CLOUDINARY_URL)
if USE_CLOUDINARY:
    INSTALLED_APPS = INSTALLED_APPS + ["cloudinary", "cloudinary_storage"]
    CLOUDINARY_STORAGE = {"SECURE": True}

# Static files are served by WhiteNoise, compressed and fingerprinted so they can be cached.
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage" if USE_CLOUDINARY
        else "django.core.files.storage.FileSystemStorage"
    },
    # Compressed, but NOT fingerprinted: one of the admin theme's stylesheets points at a
    # source-map file it does not ship, and the fingerprinting storage treats that as fatal.
    # Compression alone is what matters here; the cache headers come from the host.
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}
WHITENOISE_AUTOREFRESH = DEBUG


# AWS Configs
# AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")

# AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")

# AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")

# AWS_S3_FILE_OVERWRITE = False

# AWS_DEFAULT_ACL = 'public-read'

# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}

# AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

# AWS_LOCATION = 'static'

# STATIC_LOCATION = 'static'

# STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{STATIC_LOCATION}/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'userauths.User'

# Site URL (the storefront; used in emails and payment redirects)
SITE_URL = env.str("SITE_URL", default="http://localhost:5173").rstrip("/")

# Business rules expressed in local time are evaluated in this timezone. The database stays UTC.
BUSINESS_TIME_ZONE = env.str("BUSINESS_TIME_ZONE", default="Asia/Kolkata")

# Stripe API Keys (optional; card payments return 503 when unset)
STRIPE_PUBLIC_KEY = env.str("STRIPE_PUBLIC_KEY", default="")
STRIPE_SECRET_KEY = env.str("STRIPE_SECRET_KEY", default="")

# Paypal API Keys (optional; PayPal verification returns 503 when unset)
PAYPAL_CLIENT_ID = env.str('PAYPAL_CLIENT_ID', default="")
PAYPAL_SECRET_ID = env.str('PAYPAL_SECRET_ID', default="")
PAYPAL_API_BASE = env.str("PAYPAL_API_BASE", default="https://api-m.sandbox.paypal.com").rstrip("/")

# Razorpay (primary payment provider). Test-mode keys start with rzp_test_.
# The key id is public (it is sent to the browser); the key secret and webhook secret never are.
RAZORPAY_KEY_ID = env.str("RAZORPAY_KEY_ID", default="")
RAZORPAY_KEY_SECRET = env.str("RAZORPAY_KEY_SECRET", default="")
RAZORPAY_WEBHOOK_SECRET = env.str("RAZORPAY_WEBHOOK_SECRET", default="")
RAZORPAY_API_BASE = env.str("RAZORPAY_API_BASE", default="https://api.razorpay.com").rstrip("/")
# Payment methods offered at checkout. Stripe and PayPal code stays in the project but is
# switched off unless listed here.
ENABLED_PAYMENT_PROVIDERS = [p.strip().lower() for p in env.list("ENABLED_PAYMENT_PROVIDERS", default=["razorpay", "cod"]) if p.strip()]
# A prepaid order still unconfirmed after this many minutes is checked with Razorpay directly.
PAYMENT_RECONCILE_AFTER_MINUTES = env.int("PAYMENT_RECONCILE_AFTER_MINUTES", default=3)
# Name shown in the Razorpay checkout window and in order emails.
STORE_NAME = env.str("STORE_NAME", default="Noore Candles")
# Days after delivery before the single review-request email is sent.
REVIEW_REQUEST_DELAY_DAYS = env.int("REVIEW_REQUEST_DELAY_DAYS", default=7)
# Hours an "create your account" link sent to a guest's order email stays valid.
ACCOUNT_CLAIM_LINK_HOURS = env.int("ACCOUNT_CLAIM_LINK_HOURS", default=48)

# Password reset links stay valid for this many minutes
PASSWORD_RESET_TOKEN_MINUTES = env.int("PASSWORD_RESET_TOKEN_MINUTES", default=30)

# Inventory
# FEFO (first expiry first out) by default; FIFO is the alternative.
STOCK_ALLOCATION_STRATEGY = env.str("STOCK_ALLOCATION_STRATEGY", default="FEFO")
# Stock held for an in-progress checkout is released after this many minutes.
STOCK_RESERVATION_TTL_MINUTES = env.int("STOCK_RESERVATION_TTL_MINUTES", default=30)
# A batch expiring within this many days is never auto-allocated to a new order.
MIN_SHELF_LIFE_ON_DISPATCH_DAYS = env.int("MIN_SHELF_LIFE_ON_DISPATCH_DAYS", default=30)
# Owner alert horizon for batches approaching expiry.
EXPIRY_ALERT_DAYS = env.int("EXPIRY_ALERT_DAYS", default=45)

# Storefront
# False (default): a struck-through price is the MRP, shown whenever MRP > selling price.
# True: a struck-through price is shown only when the price history proves a higher price was
# charged during PRICE_HISTORY_WINDOW_DAYS before the current price took effect.
STRIKETHROUGH_REQUIRES_PRICE_HISTORY = env.bool("STRIKETHROUGH_REQUIRES_PRICE_HISTORY", default=False)
PRICE_HISTORY_WINDOW_DAYS = env.int("PRICE_HISTORY_WINDOW_DAYS", default=30)
# "Only N left" is shown when the real available quantity is at or below this number.
LOW_STOCK_THRESHOLD = env.int("LOW_STOCK_THRESHOLD", default=5)

# Running background jobs over HTTP.
#
# Order emails, payment reconciliation and checkout expiry normally run in `manage.py
# run_worker`. Hosting that cannot run a second process (free tiers) can instead call
#   POST /api/v1/jobs/run/   with header  X-Jobs-Token: <this value>
# from any scheduler (a GitHub Actions workflow, cron-job.org, Windows Task Scheduler).
# Blank (the default) disables the endpoint completely: it answers 404 as if it did not exist.
JOBS_RUN_TOKEN = env.str("JOBS_RUN_TOKEN", default="")
JOBS_RUN_BATCH = env.int("JOBS_RUN_BATCH", default=50)

# Orders
# An unpaid order draft older than this is expired by the worker: its stock holds and its
# coupon use are given back. Must stay above 26 (a card payment session can stay open a day).
ORDER_DRAFT_TTL_HOURS = env.int("ORDER_DRAFT_TTL_HOURS", default=48)

# Job worker (python manage.py run_worker)
JOB_MAX_ATTEMPTS = env.int("JOB_MAX_ATTEMPTS", default=5)
JOB_WORKER_SLEEP_SECONDS = env.float("JOB_WORKER_SLEEP_SECONDS", default=5.0)
JOB_STALE_AFTER_SECONDS = env.int("JOB_STALE_AFTER_SECONDS", default=600)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'core.authentication.AuditingJWTAuthentication',
    ),
    # Default-deny: every view must opt in to public access explicitly.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': env.str("THROTTLE_ANON", default="300/min"),
        'user': env.str("THROTTLE_USER", default="600/min"),
        'auth': env.str("THROTTLE_AUTH", default="10/min"),
        'otp': env.str("THROTTLE_OTP", default="5/min"),
        'checkout': env.str("THROTTLE_CHECKOUT", default="60/min"),
        'review': env.str("THROTTLE_REVIEW", default="10/min"),
        'webhook': env.str("THROTTLE_WEBHOOK", default="600/min"),
    },
}

ANYMAIL = {
    "MAILGUN_API_KEY": env.str("MAILGUN_API_KEY", default=""),
    "MAILGUN_SENDER_DOMAIN": env.str("MAILGUN_SENDER_DOMAIN", default=""),
}

# Use django.core.mail.backends.console.EmailBackend in development to print emails.
EMAIL_BACKEND = env.str("DJANGO_EMAIL_BACKEND", default="anymail.backends.mailgun.EmailBackend")
FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", default="noreply@localhost")
DEFAULT_FROM_EMAIL = FROM_EMAIL
SERVER_EMAIL = FROM_EMAIL

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=["http://localhost:5173", "http://127.0.0.1:5173"])

# Logging: every handler masks emails, phone numbers and tokens.
LOG_LEVEL = env.str("LOG_LEVEL", default="INFO")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "mask_pii": {"()": "core.logmask.PIIMaskingFilter"},
    },
    "formatters": {
        "standard": {"format": "%(asctime)s %(levelname)s %(name)s: %(message)s"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
            "filters": ["mask_pii"],
        },
    },
    "root": {"handlers": ["console"], "level": LOG_LEVEL},
    "loggers": {
        "django": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
    },
}

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Production runs behind Caddy, which terminates HTTPS and forwards X-Forwarded-Proto.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=True)
    # The health check is called over plain HTTP from the server itself.
    SECURE_REDIRECT_EXEMPT = [r"^api/v1/health/$"]
    # HSTS tells browsers to refuse plain HTTP for this long. Start small (an hour) and raise
    # it to a year (31536000) once HTTPS has been working for a while: it cannot be taken back
    # quickly. See docs/DEPLOY.md.
    SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=3600)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)
    SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=False)
    SECURE_REFERRER_POLICY = "same-origin"
    X_FRAME_OPTIONS = "DENY"

# Cache. Rate limits (DRF throttling) are counted in the cache, so with more than one server
# process the cache must be shared or each process would keep its own count (bug D14).
#   locmem  per-process memory: fine for development and tests (the default when DEBUG is on)
#   db      a database table shared by every process (the default when DEBUG is off);
#           create it once with:  python manage.py createcachetable
DJANGO_CACHE = env.str("DJANGO_CACHE", default="locmem" if DEBUG else "db").lower()
if DJANGO_CACHE == "db":
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.db.DatabaseCache", "LOCATION": "django_cache"}}
else:
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache", "LOCATION": "default"}}

# Error reports. When set, every ERROR logged by the backend is emailed here (PII-masked, at
# most one email per distinct error every few minutes). Comma-separated addresses.
ERROR_REPORT_EMAILS = [a.strip() for a in env.list("ERROR_REPORT_EMAILS", default=[]) if a.strip()]
ERROR_REPORT_MIN_INTERVAL_SECONDS = env.int("ERROR_REPORT_MIN_INTERVAL_SECONDS", default=300)
if ERROR_REPORT_EMAILS:
    LOGGING["handlers"]["error_email"] = {
        "class": "core.error_email.ErrorEmailHandler",
        "level": "ERROR",
        "filters": ["mask_pii"],
    }
    LOGGING["root"]["handlers"].append("error_email")
    LOGGING["loggers"]["django"]["handlers"].append("error_email")

# The health check reports the background worker as down when no job has finished for this long.
WORKER_STALE_AFTER_SECONDS = env.int("WORKER_STALE_AFTER_SECONDS", default=300)

# Absolute path of the built storefront page (frontend/dist/index.html). When set, product
# URLs requested from the server get that page with the product's title, description, price
# and image filled into the <head>, so links shared on WhatsApp and social media show a
# proper preview. Leave unset in development.
FRONTEND_INDEX_PATH = env.str("FRONTEND_INDEX_PATH", default="")


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=50),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',

    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}


JAZZMIN_SETTINGS = {
    "site_title": "Desphixs",
    "site_header": "Desphixs",
    "site_brand": "Modern Marketplace ",
    "site_icon": "images/favicon.ico",
    "site_logo": "images/logos/logo.jpg",
    "welcome_sign": "Welcome To Desphixs",
    "copyright": "All right reserved to Desphixs",
    "user_avatar": "images/photos/logo.jpg",
    "topmenu_links": [
        {"name": "Dashboard", "url": "home",
            "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": [
        "store",
        "store.product",
        "store.cartorder",
        "store.cartorderitem",
        "store.cart",
        "store.category",
        "store.brand",
        "store.productfaq",
        "store.review",
        "store.Coupon",
        "store.DeliveryCouriers",
        "userauths",
        "userauths.user",
        "userauths.profile",
    ],
    "icons": {
        "admin.LogEntry": "fas fa-file",

        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",

        "userauths.User": "fas fa-user",
        "userauths.Profile": "fas fa-address-card",

        "store.Product": "fas fa-th",
        "store.CartOrder": "fas fa-shopping-cart",
        "store.Cart": "fas fa-cart-plus",
        "store.CartOrderItem": "fas fa-shopping-basket",
        "store.Brand": "fas fa-check-circle",
        "store.productfaq": "fas fa-question",
        "store.Review": "fas fa-star fa-beat",
        "store.Category": "fas fa-tag",
        "store.Coupon": "fas fa-percentage",
        "store.DeliveryCouriers": "fas fa-truck",
        "store.Address": "fas fa-location-arrow",
        "store.Tag": "fas fa-tag",
        "store.Wishlist": "fas fa-heart",
        "store.Notification": "fas fa-bell",

    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-arrow-circle-right",
    "related_modal_active": False,

    "custom_js": None,
    "show_ui_builder": False,

    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-indigo",
    "accent": "accent-olive",
    "navbar": "navbar-indigo navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-indigo",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cyborg",
    "dark_mode_theme": "cyborg",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}