# Generated by Django 4.2.7 on 2026-09-27 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('store', '0027_deliverycouriers_url_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='channel',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('AMAZON', 'Amazon'), ('FLIPKART', 'Flipkart'), ('QCOMM', 'Quick commerce'), ('OFFLINE', 'Offline'), ('MANUAL', 'Manual')], default='WEBSITE', max_length=20),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('CARD', 'Card'), ('NETBANKING', 'Netbanking'), ('WALLET', 'Wallet'), ('COD', 'Cash on Delivery')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='phone_e164',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant'),
        ),
    ]
