# Generated by Django 4.2.7 on 2026-10-02 22:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0033_coupon_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('phone_e164', models.CharField(blank=True, default='', max_length=20)),
                ('discount_paise', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='store.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to='store.cartorder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['coupon', 'email'], name='store_coupo_coupon__2fa7b5_idx'), models.Index(fields=['coupon', 'phone_e164'], name='store_coupo_coupon__7e93ee_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='couponredemption',
            constraint=models.UniqueConstraint(fields=('coupon', 'order'), name='store_couponredemption_coupon_order_uniq'),
        ),
    ]
