# Generated by Django 4.2.7 on 2026-10-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0004_currency_inr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configsettings',
            name='currency_abbreviation',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='configsettings',
            name='currency_sign',
            field=models.CharField(default='₹', max_length=10),
        ),
    ]
