# Generated by Django 4.2.7 on 2026-09-27 10:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0028_variant_channel_cod_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=64, unique=True)),
                ('manufactured_on', models.DateField()),
                ('best_before', models.DateField(blank=True, null=True)),
                ('quantity_produced', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cost_per_unit_paise', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('production_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.productvariant')),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['best_before', 'manufactured_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CONSUMED', 'Consumed'), ('RELEASED', 'Released'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('cart_id', models.CharField(blank=True, db_index=True, max_length=1000)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.batch')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='store.cartorder')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='store.cartorderitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='inventory_s_status_c656ef_idx'), models.Index(fields=['variant', 'status'], name='inventory_s_variant_f89c3b_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PRODUCTION_IN', 'Production in'), ('SALE_OUT', 'Sale out'), ('RETURN_IN', 'Customer return in'), ('RTO_IN', 'RTO in'), ('DAMAGE_OUT', 'Damage / write-off out'), ('ADJUSTMENT', 'Manual adjustment')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Signed: positive is stock in, negative is stock out.')),
                ('channel', models.CharField(choices=[('WEBSITE', 'Website'), ('AMAZON', 'Amazon'), ('FLIPKART', 'Flipkart'), ('QCOMM', 'Quick commerce'), ('OFFLINE', 'Offline'), ('MANUAL', 'Manual')], default='WEBSITE', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('actor_label', models.CharField(default='system', max_length=100)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.batch')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['variant', 'created_at'], name='inventory_s_variant_183f66_idx'), models.Index(fields=['batch', 'created_at'], name='inventory_s_batch_i_8a6d71_idx'), models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_5aaa1a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['variant', 'best_before'], name='inventory_b_variant_31e254_idx'),
        ),
    ]
